services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data 
    env_file:
      - ../../.env.local
volumes:
  pgdata:
